version: 2
jobs:
    frontend:
        docker:
            - image: circleci/node:12.16.1
        steps:
            - checkout
            - run: 
                command: cd ./app && npm install && npm run build
    server:
        docker:
            - image: circleci/node:12.16.1
        steps:
            - checkout
            - run: 
                command: cd ./server && npm install && npm run start
workflows:
    version: 2
    build_test:
        jobs:
            - frontend
            - server
