version: 2
jobs:
    frontend:
        docker:
            - image: circleci/node:12.16.1
        steps:
            - checkout
            - run: cd app
            - run: npm install
            - run: npm run build
    server:
        docker:
            - image: circleci/node:12.16.1
            steps:
                - checkout
                - run: cd server
                - run: npm install
                - run: npm run start
workflows:
    version: 2
    build_test:
        jobs:
            - frontend
            - server
